version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
     dependencies:
        patterns:
          - "*"
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
     dependencies:
        patterns:
          - "*"
