apiVersion: v1
kind: Service
metadata:
  name: {{ include "openfga.fullname" . }}
  labels:
    {{- include "openfga.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ (split ":" .Values.grpc.addr)._1 }}
      targetPort: grpc
      protocol: TCP

    {{- if .Values.http.enabled }}
    - name: http 
      port: {{ (split ":" .Values.http.addr)._1 }}
      targetPort: http
      protocol: TCP
    {{- end }}

    {{- if .Values.profiler.enabled }}
    - name: profiler
      port: {{ (split ":" .Values.profiler.addr)._1 }}
      targetPort: profiler
      protocol: TCP
    {{- end }}

    {{- if .Values.playground.enabled }}
    - name: playground
      port: {{ .Values.playground.port }}
      targetPort: playground
      protocol: TCP
    {{- end }}

    {{- if .Values.telemetry.metrics.enabled }}
    - name: metrics
      port: {{ (split ":" .Values.telemetry.metrics.addr)._1 }}
      targetPort: metrics
      protocol: TCP
    {{- end }}

  selector:
    {{- include "openfga.selectorLabels" . | nindent 4 }}
